# Generated by Django 6.0.1 on 2026-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card_images/')),
                ('prompt', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('elo_rating', models.FloatField(default=1200.0)),
                ('submitted_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
