# Generated by Django 6.0.1 on 2026-01-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate an 8-letter password.', max_length=128),
        ),
    ]
