# Generated by Django 6.0.1 on 2026-01-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_duel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='judge',
        ),
    ]
