# Generated by Django 6.0.1 on 2026-01-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_participant_card_uploader_duel_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='submitted_by',
        ),
    ]
