# Generated by Django 6.0.1 on 2026-01-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_results_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other/Prefer not to say')], default='O', max_length=1),
        ),
    ]
