# Generated by Django 6.0.1 on 2026-01-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_participant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='elo_rating_men',
            field=models.FloatField(default=1200.0),
        ),
        migrations.AddField(
            model_name='card',
            name='elo_rating_women',
            field=models.FloatField(default=1200.0),
        ),
    ]
