# Generated by Django 6.0.1 on 2026-02-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_card_elo_rating_men_card_elo_rating_women'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='elo_rating',
        ),
        migrations.RemoveField(
            model_name='card',
            name='elo_rating_men',
        ),
        migrations.RemoveField(
            model_name='card',
            name='elo_rating_women',
        ),
    ]
