# Generated by Django 6.0.1 on 2026-02-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_card_elo_rating_remove_card_elo_rating_men_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Mann'), ('F', 'Kvinne'), ('O', 'Annet/foretrekker å ikke si')], default='O', max_length=1),
        ),
    ]
