# Generated by Django 6.0.1 on 2026-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_participant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voting_enabled',
            field=models.BooleanField(default=True, help_text='Check this to enable voting and card submission for this profile.'),
        ),
    ]
