# Generated by Django 6.0.1 on 2026-02-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_voting_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='card_videos/'),
        ),
    ]
