# Generated by Django 6.0.1 on 2026-02-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_card_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='random_prompts_mode',
            field=models.BooleanField(default=False, help_text='If checked, participants will be assigned a random prompt instead of choosing.'),
        ),
    ]
